name: Build & Push users-service to ECR

on:
  push:
    paths:
      - 'app/users-service/**'
      - '.github/workflows/users-service.yml'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: users-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::571600835023:role/github-actions-ecr-push
        role-session-name: github-actions
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
        docker build -t $IMAGE_URI ./app/orders-service
        docker push $IMAGE_URI
